---
kind: pipeline
name: testing

platform:
  os: linux
  arch: amd64

steps:
- name: prepare
  image: webhippie/php-cli:latest
  pull: always
  commands:
  - composer install --prefer-dist

- name: stan
  image: webhippie/php-cli:latest
  pull: always
  commands:
  - ./vendor-bin/stan/vendor/bin/phpstan analyse --level=5 lib/
  depends_on:
  - prepare

- name: phan
  image: webhippie/php-cli:latest
  pull: always
  commands:
  - ./vendor-bin/phan/vendor/bin/phan --allow-polyfill-parser lib/**/*.php
  depends_on:
  - prepare

- name: test
  image: webhippie/php-cli:latest
  pull: always
  commands:
  - ./vendor-bin/phpunit/vendor/bin/phpunit tests/
  depends_on:
  - prepare

- name: notify
  image: plugins/matrix:1
  pull: always
  settings:
    username:
      from_secret: matrix_username
    password:
      from_secret: matrix_password
    roomid:
      from_secret: matrix_roomid
  when:
    event:
    - push
    - tag
    status:
    - failure
  depends_on:
  - prepare
  - stan
  - phan
  - test

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**
