<?php
/**
 * TeamApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Umschlag
 * @author   Thomas Boerger <thomas@webhippie.de>
 * @license  http://www.apache.org/licenses/LICENSE-2.0.html Apache-2.0
 * @link     https://github.com/umschlag/umschlag-php
 */

/**
 * Umschlag OpenAPI
 *
 * API definition for Umschlag
 *
 * The version of the OpenAPI document: 1.0.0-alpha1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Umschlag;

use \Umschlag\Configuration;
use \Umschlag\ApiException;
use \Umschlag\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TeamApiTest Class Doc Comment
 *
 * @category Class
 * @package  Umschlag
 * @author   Thomas Boerger <thomas@webhippie.de>
 * @license  http://www.apache.org/licenses/LICENSE-2.0.html Apache-2.0
 * @link     https://github.com/umschlag/umschlag-php
 */
class TeamApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for appendTeamToUser
     *
     * Assign a user to team.
     *
     */
    public function testAppendTeamToUser()
    {
    }

    /**
     * Test case for createTeam
     *
     * Create a new team.
     *
     */
    public function testCreateTeam()
    {
    }

    /**
     * Test case for deleteTeam
     *
     * Delete a specific team.
     *
     */
    public function testDeleteTeam()
    {
    }

    /**
     * Test case for deleteTeamFromUser
     *
     * Remove a user from team.
     *
     */
    public function testDeleteTeamFromUser()
    {
    }

    /**
     * Test case for listTeamUsers
     *
     * Fetch all users assigned to team.
     *
     */
    public function testListTeamUsers()
    {
    }

    /**
     * Test case for listTeams
     *
     * Fetch all available teams.
     *
     */
    public function testListTeams()
    {
    }

    /**
     * Test case for permitTeamUser
     *
     * Update user perms for team.
     *
     */
    public function testPermitTeamUser()
    {
    }

    /**
     * Test case for showTeam
     *
     * Fetch a specific team.
     *
     */
    public function testShowTeam()
    {
    }

    /**
     * Test case for updateTeam
     *
     * Update a specific team.
     *
     */
    public function testUpdateTeam()
    {
    }
}
