<?php
/**
 * UserApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Umschlag
 * @author   Thomas Boerger <thomas@webhippie.de>
 * @license  http://www.apache.org/licenses/LICENSE-2.0.html Apache-2.0
 * @link     https://github.com/umschlag/umschlag-php
 */

/**
 * Umschlag OpenAPI
 *
 * API definition for Umschlag
 *
 * The version of the OpenAPI document: 1.0.0-alpha1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Umschlag;

use \Umschlag\Configuration;
use \Umschlag\ApiException;
use \Umschlag\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * UserApiTest Class Doc Comment
 *
 * @category Class
 * @package  Umschlag
 * @author   Thomas Boerger <thomas@webhippie.de>
 * @license  http://www.apache.org/licenses/LICENSE-2.0.html Apache-2.0
 * @link     https://github.com/umschlag/umschlag-php
 */
class UserApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for appendUserToTeam
     *
     * Assign a team to user.
     *
     */
    public function testAppendUserToTeam()
    {
    }

    /**
     * Test case for createUser
     *
     * Create a new user.
     *
     */
    public function testCreateUser()
    {
    }

    /**
     * Test case for deleteUser
     *
     * Delete a specific user.
     *
     */
    public function testDeleteUser()
    {
    }

    /**
     * Test case for deleteUserFromTeam
     *
     * Remove a team from user.
     *
     */
    public function testDeleteUserFromTeam()
    {
    }

    /**
     * Test case for listUserTeams
     *
     * Fetch all teams assigned to user.
     *
     */
    public function testListUserTeams()
    {
    }

    /**
     * Test case for listUsers
     *
     * Fetch all available users.
     *
     */
    public function testListUsers()
    {
    }

    /**
     * Test case for permitUserTeam
     *
     * Update team perms for user.
     *
     */
    public function testPermitUserTeam()
    {
    }

    /**
     * Test case for showUser
     *
     * Fetch a specific user.
     *
     */
    public function testShowUser()
    {
    }

    /**
     * Test case for updateUser
     *
     * Update a specific user.
     *
     */
    public function testUpdateUser()
    {
    }
}
